### ISSUE TITLE
Regarding Login problem

### ISSUE THREAD

**Issue by suhandhan** [julionery/lubiju-admin-flutter-firebase#1]
Hi. I cannot able to login which i have connected to my firestore database. Even i have enable the email authentication. please tell me to how to  set the "security rules" and "Admin Authentication"!!

**Comment by julionery** [comment]
Hi, sorry, I forgot to explain how to enable admin users.

To access this application you need:

1. Enable email authentication;
![Screenshot_2](https://user-images.githubusercontent.com/15279868/93206022-1d944000-f72f-11ea-8480-a094936615c7.jpg)

2. Add a new user and copy the UID;
![Screenshot_5](https://user-images.githubusercontent.com/15279868/93206074-33096a00-f72f-11ea-9c20-6a991e137d3a.jpg)
![Screenshot_1](https://user-images.githubusercontent.com/15279868/93206109-46b4d080-f72f-11ea-92b6-0af882293067.jpg)

3. Create a new collection with the name "admins" and create a new document with the Document ID and a field with the name "uid" with the UID of the users who will be the administrator.
![Screenshot_4](https://user-images.githubusercontent.com/15279868/93206133-52a09280-f72f-11ea-9fe6-e716f78f84fe.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/15279868/93206146-56341980-f72f-11ea-9dd3-8f6bfb16291c.jpg)

**Comment by suhandhan** [comment]
Thank you very much for sharing the information and i have one more request . please, can you share about how to defined the security rules for admin access in firestore!!

**Comment by julionery** [comment]
I created a function to check the administrator on the firestore rules.
![image](https://user-images.githubusercontent.com/15279868/93253623-86021200-f76d-11ea-84af-d0624a2b31df.png)

Follow my firestore rules for example:
- [Firestore Rules](https://github.com/julionery/lubiju-admin-flutter-firebase/blob/master/firebase_rules.txt)

**Comment by suhandhan** [comment]
Thank you so much for your guidance
